### ISSUE TITLE
GUI doesn't launch anymore

### ISSUE THREAD

**Issue by DanMan** [KrossX/Durazno#12]
The GUI won't launch anymore. Might have to do with some recent Windows updates. I'm on Win7 Home 64bit. Here's the error:

>   Problem event name:	CLR20r3
>   Problem signature 01:	Durazno.exe
>   Problem signature 02:	0.6.0.0
>   Problem signature 03:	56d8cc61
>   Problem signature 04:	mscorlib
>   Problem signature 05:	4.0.30319.34209
>   Problem signature 06:	53489fcf
>   Problem signature 07:	eb0
>   Problem signature 08:	5a
>   Problem signature 09:	System.Windows.Markup.XamlParse
>   OS version:	6.1.7601.2.1.0.768.3

**Comment by KrossX** [comment]
Try downloading the latest one again, extract it into an empty folder and run it from there.

**Comment by DanMan** [comment]
Alright. That worked. Turns out, the config file was the problem: http://pastebin.com/Pp3SAu7G

**Comment by KrossX** [comment]
Nice, thanks for the config data.

**Comment by KrossX** [comment]
Added a workaround against weird strings. Did you try to make the setting manually?

**Comment by DanMan** [comment]
No, not that I remember.
