### ISSUE TITLE
how keep 180 quick turn and crosshair short move precision same time in fps

### ISSUE THREAD

**Issue by cloudslsw** [KrossX/Durazno#13]
i play doom open beta use gamepad and i almost kill no one,stick aim often over cross target,i decreced sensitivity in game but when i fire some one behind me,i hardly turn 180 back,,there just vertical and horitional sensitivity i can adjust in game,is there a way to use Durazno to keep these two things samt time? thanks

**Comment by KrossX** [comment]
Let me see if I understand it. You lowered the sensitivity to get some finer aim control, but that makes it impossible to get a fast turn.

If so, I suggest to change the ingame sensitivity until you can turn quickly enough. Then with Durazno, increase the linearity to 2 or higher. A positive linearity will make it low sensitivity on the center with high sensitivity on the edge, so you should have a finer aim with a quick turn on the edge of the stick. This works best with little to no deadzone if the game allows to change that.

**Comment by cloudslsw** [comment]
oh boss i try and i can't say it actually working as intended but i think its getting better after sensitivity and  linearity adjust,maybe i should find best number for me,and priactice gamepad for fps,thanks for pro advice :D
