### ISSUE TITLE
Am I missing something here? (Dead Space)

### ISSUE THREAD

**Issue by InformalMoose** [KrossX/Durazno#15]
So I followed the PcGaming wiki here to fix the controller deadzones. The instructions say to open Durazno.exe but it's not in any of the folders that was in the download. I didn't get any Durazno.ini or DLL either.

**Comment by KrossX** [comment]
Binaries are not hosted on Github, you can download them from the following link that can be found on the project Readme: http://tiny.cc/magicaltools

**Comment by InformalMoose** [comment]
Oh shit ok thank you much
