### ISSUE TITLE
Attack on Titan PC

### ISSUE THREAD

**Issue by jvook** [KrossX/Durazno#17]
This game (attack on titan) has awful deadzone defaults an no options so I gave this Durazno software a try but I can't seem to get it working.

It is a x64 game so I'm using the x64 xinput1_3.dll (of course I tried the 32 bit as well).  I also tried all the other names.  But I think it's xinput1_3.dll because Durazno log says this:
= Durazno Log Opened =
DllMain: DLL_PROCESS_ATTACH
XInputLoadLibrary: C:\WINDOWS\system32\xinput1_3.dll
XInputGetProc: XInputGetStateEx

So it seems to be detecting the file but the settings I do make no difference in the game.

I followed the link in the readme to the x360ce wiki; game is brand new so no listing there.  (By the way, you need to update the URL in the readme to https://github.com/x360ce/x360ce/wiki/Compatibility-List)

Anyway I think I might need to do the hookmask thing they mention on that page but I have no idea how to do this in Durazno:

 > HookLL
> 
> Many XACT games (that is, the Xbox360/PC cross platform games) require HookLL to run properly. As they do not load the xinput runtime directly, Dinput8 wrapper is required to redirect back to the local X360CE binary instead of loading the default xinput1/9_x binary.

**Comment by KrossX** [comment]
If you got the log then it's correctly in place, there's no hooking in Durazno though it's a simple wrapper. You might wanna try with [XInput Plus](https://sites.google.com/site/0dd14lab/xinput-plus).

**Comment by jvook** [comment]
Thanks bro I'll try the program.  Is it only in Japanese?

**Comment by KrossX** [comment]
It does work in english too if I remember correctly.

**Comment by jvook** [comment]
Yeah it worked thanks
