### ISSUE TITLE
64bit support

### ISSUE THREAD

**Issue by DanMan** [KrossX/Durazno#2]
New games often come exclusively in 64bit versions, but Durazno doesn't support them, does it?

X360ce provides 64bit XInput dlls, but unfortunately you can't just use those to replace the one coming with Durazno. So a 64bit version would be very appreciated.

**Comment by puddle82** [comment]
i signed up for an account just to say: 
THANK YOU!!! as someone who first started 3d gaming playing flight sims and some old star wars flying game with a joystick, fully inverted controls are the only way my brain works and you solved my problem with shadow of mordor - i was ready to just give up playing and accept the fact that WB got my money and i got nothing, but not anymore! i can play it after all!! THANK YOU THANK YOU!

**Comment by KrossX** [comment]
You're welcome. =D
