### ISSUE TITLE
[request] custom fomula sensitivity remapping

### ISSUE THREAD

**Issue by shadoxxhd** [KrossX/Durazno#25]
you could enter a small script (or similiar - fomula, asm code or whatever) that would transform input x/y into the x/y values that are sent to the game

the reason I want this is that I want to sort of 'separate' the x and y axis: when I'm in a 'corner', it should be at 1/1 instead of sqrt(2)/sqrt(2) (this means basically a circle to square remapping).

**Comment by KrossX** [comment]
Allowing custom scripts to be run is an enormous task I have no idea how to do. The best that can be allowed is... using the available source code for your own custom Durazno! =D  There's actually custom Durazno that tries to do just that, you might wanna give it a try, it's called Durazno Square or similar.

**Comment by shadoxxhd** [comment]
I really appreciate the reply - durazno square should be exactly what I need!
On a sidenote, letting the user input raw bytecode to run should be really easy - since the user would input the code himself, the program wouldn't need to worry about security etc.
