### ISSUE TITLE
Opening two instances of the GUI crashes it

### ISSUE THREAD

**Issue by Keith94** [KrossX/Durazno#26]
As the title says, double-clicking `Duranzo.exe` while it's still running crashes the program.

**Comment by KrossX** [comment]
I'll give it a check.

**Comment by Keith94** [comment]
Is it reproducible?

**Comment by KrossX** [comment]
I completely forgot about this.

I checked and is indeed reproducible. For some reason, the second instance cannot load durazno's dll. If I just use the system dll directly, there's no problem. Thus, the problem must be on the wrapper dll.

**Comment by Keith94** [comment]
I just noticed your edit. Yes, it's fixed in the latest version.
