### ISSUE TITLE
+5% constant CPU usage

### ISSUE THREAD

**Issue by notnsane** [KrossX/Durazno#29]
Note that this is doing absolutely nothing: https://a.pomf.cat/comorz.webm

[Zipped video in case it gets deleted ](https://github.com/KrossX/Durazno/files/688960/comorz.zip)

**Comment by KrossX** [comment]
Yup, the GUI is quite inefficient. The one time I tried to optimize it, it made everything quite sluggish so I left it as it is. You're not supposed to leave it running though, it's only to make a settings file or test it.

**Comment by notnsane** [comment]
I'm going then to go ahead and close it and keep it as a non-issue!
