### ISSUE TITLE
Games using xinput1_3.dll from system32 or sysWOW64 folder

### ISSUE THREAD

**Issue by RixzZ** [KrossX/Durazno#3]
Hello, I'm trying to make my f710 controller vibration work well with The Crew. After some changes I noticed that The Crew is loading the xinput1_3.dll from SysWOW64 folder.

I tried to replace it with your dll (x64 version) but it doesn't work. I also tried before to use it from game folder but it ignores it.

Is there a way to make it work for games that uses the xinput dll from system32 or sysWOW64 folder?

Thanks.

**Comment by KrossX** [comment]
Durazno requries those files to work, so replacing it with them ain't a good idea. To get a global durazno, I guess renaming the originals might work. The INI file has a LoadDLL entry, you can try and use that one.

For example, rename the original xinput1_3.dll to xinput1_3_old.dll, then copy durazno's dll over it and edit the INI's LoadDLL entry to point to xinput1_3_old.dll. Might work, but I don't think a global wrapper is a good idea. =S

**Comment by RixzZ** [comment]
I'll try that way but yep, I think is not a good solution but it seems not to be other way. I suppose is not possible specify where the game look for the .dll file.

Thanks for your answer.

**Comment by mirh** [comment]
I guess they might be using [LOAD_LIBRARY_SEARCH_SYSTEM32](https://msdn.microsoft.com/en-us/library/windows/desktop/ms684179.aspx) ?

**Comment by KrossX** [comment]
Or similar, but Durazno could certainly make use of it.

**Comment by mirh** [comment]
Well, it's not like they couldn't have [force](https://github.com/PCSX2/pcsx2/pull/1237/commits/834652922a0953a17cbd8fa5063539cf0321dc1b) the [dll](https://github.com/PCSX2/pcsx2/pull/1238/commits/8f4823d60413a0581ecc0b0580e6c388a80b23f0#diff-5fa8a882d01c9105bf7f5c58c525f660R166) path in the first place either (for as much as it seems dumb)
But regardless even if it was about LoadLibraryEx, I guess it should be possible to support that even if the program still targets [XP](https://git.merproject.org/mer-core/gecko-dev/commit/1ff02048267cadaefec55d8dc97beba4f3b8fd87) (and kudos for that anyway). 

I think I already had this kind of problems some time ago.. I don't remember how I managed to bypass it though. Perhaps any of [these](https://msdn.microsoft.com/en-us/library/windows/desktop/ms682586.aspx#search_order_for_desktop_applications) registry tricks?

**Comment by KrossX** [comment]
A registry change would require admin rights and affect more than just the current game running. Though in case of making some global Durazno, I guess a service and a loadlibrary hook would be more reliable. There's also the case where other services already do this to capture xinput readings and might compete in weird ways. Another option, custom controller driver with xinput support... yeah right.

**Comment by KrossX** [comment]
I am not sure of anything as I have no way to test this game. The issue itself is pretty old though, maybe things changed or maybe no one plays it anymore.

**Comment by mirh** [comment]
There's a demo on uplay, for the records. 
But yes, OP mistaking is more probable.

**Comment by KrossX** [comment]
I had completely forgotten uplay existed, I'll keep it in mind in case the issue repeats.
