### ISSUE TITLE
[Feature Request] Separate left trigger and right trigger deadzone options

### ISSUE THREAD

**Issue by knightzx** [KrossX/Durazno#32]
As of v0.6-29 left trigger and right trigger deadzone share one option
I needs to set deadzone for my xbox 360 controller's right trigger to get it working but I still want to keep using the left trigger as it is.
Any chance you can add these options to your program?

**Comment by KrossX** [comment]
It shouldn't be too hard I think.

**Comment by knightzx** [comment]
It works now.
Thank you very much for your program.
