### ISSUE TITLE
Build xinput1_3.dll failed

### ISSUE THREAD

**Issue by yxmline** [KrossX/Durazno#33]
Durazno.cpp(215): error C2733: “XInputGetBatteryInformation
Durazno.cpp(227): error C2733: “XInputGetKeystroke
Find the reason for adding DirectX sdk to cause an error

**Comment by KrossX** [comment]
Do not include unnecessary SDKs.

**Comment by yxmline** [comment]
thanks

**Comment by KrossX** [comment]
Excellent! I'll mark this closed then.
