### ISSUE TITLE
Quantum Break

### ISSUE THREAD

**Issue by zitrish** [KrossX/Durazno#34]
HI!

How could I get Durazno to work with Quantum Break? Is there any specific configuration? It doesn't seem to recongnize the wrapper. I have tried with x64 versions of xinput1_3.dll and xinput9_1_0.dll, but not working. I used Xinput Plus as well and still not luck.

I will be grateful for any help you can provide.

**Comment by KrossX** [comment]
No idea, a google search didn't help either. You could try  DependencyWalker and see what dlls the game looks for.

It is also possible that even if the game uses XInput, it might be looking for the system files directly to protect against wrappers and such.

**Comment by zitrish** [comment]
Thank you for the answer KrossX!

I have tried with XInput1_4.dll and it worked flawlessly :)

Thank you so much for your work and help. You can close this issue now! ;)

**Comment by KrossX** [comment]
Roger that, glad it's working. Have fun!
