### ISSUE TITLE
Deadzone not applying

### ISSUE THREAD

**Issue by Gfurst** [KrossX/Durazno#38]
Help, I can't for the life of me why this is happening, picture shows the left stick with a slight drift forwards, with a deadzone of 90%, it seems to apply to the other stick, and even to the X axis of the left stick, but not the Y axis where the drift actually exists. And as you can see from picture, the drift bad and jittery.

![2017-11-21 01_11_18-durazno](https://user-images.githubusercontent.com/12454141/33053083-f40916ea-ce58-11e7-94e8-a466b53454b9.jpg)
![2017-11-21 01_13_24-durazno](https://user-images.githubusercontent.com/12454141/33053179-6755cf76-ce59-11e7-8ef6-0f6b1735fbc6.jpg)

**Comment by KrossX** [comment]
I just tested it with "Durazno v0.6-41" and it worked fine. =S

Can you check this [test-dll](https://drive.google.com/file/d/0B1wssOeJs5_7MTBYcjd3UlVCS3c/view) please? It's for 32bit Durazno, just replace the dll in there with this one.

**Comment by Gfurst** [comment]
I was also using v0.6-41, got this joystick just last week, and am seriously considering returning it.  
Anyway, it seems it handles better than before, however it still sort of rests off center like in picture.  
Actually further testing right now to get picture showed the exact issue, if the movement is only on the Y axis then the deadzone is not applied, as soon as move sideways it works.

![2017-11-21 12_29_11-durazno](https://user-images.githubusercontent.com/12454141/33077940-4e5fde1c-ceb8-11e7-8451-6370500a236a.jpg)
![2017-11-21 12_32_31-durazno](https://user-images.githubusercontent.com/12454141/33077941-4e89f990-ceb8-11e7-8260-2ccf1ec30902.jpg)

**Comment by KrossX** [comment]
Can you attach your INI file please?

**Comment by Gfurst** [comment]
Hey you nailed it! Seems to be working as intended now. Thanks!  
Can I just use the same dll and rename for the other needs? And do you still want the config file?

![2017-11-21 15_32_41-durazno](https://user-images.githubusercontent.com/12454141/33087388-92129dc0-ced1-11e7-9ed3-8c54d03525ed.jpg)

**Comment by KrossX** [comment]
No need for the config files anymore. As for the dll, you might reuse it for a lower version but functions will be missing for a higher version dll. I'll try to get some builds later today though.

**Comment by Gfurst** [comment]
Thanks, let us know when you release it and close the issue.

Fyi, on the hardware side of things, it seems to have helped quite a lot to use an air blower over the mechanism, and then lubricate it with light machine oil, move it to let it spread and let it rest for a while. You should try that if your sticks are really too bad.

**Comment by KrossX** [comment]
Roger that, I'll close it then. The new build is "Durazno v0.6-43", please see if works as expected.

As for the controller, it never centered at perfect zero but now it's very loose so it's even harder to keep it around the center. Nothing that some huge deadzone can't fix. =P
