### ISSUE TITLE
Can't get Durazno to work with Dead Space

### ISSUE THREAD

**Issue by SnowGabe** [KrossX/Durazno#4]
The deadzone in Dead Space is massive, the game is literally unplayable.
I downloaded Durazno and followed the instructions (information might be outdated; I will update the article if there are any issues) on PC Gaming Wiki: http://pcgamingwiki.com/wiki/Dead_Space#Large_deadzone
Durazno.ini and xinput1_3.dll are in my installation folder.

Is everything set correctly in my Durazno.ini?

"[General]
INIversion=3
LoadDLL=
[Controller0]
Port=0
Disable=0
Dummy=0
LinearDZ=0
LinearADZ=0
AxisInvertedLX=0
AxisInvertedLY=0
AxisInvertedRX=0
AxisInvertedRY=0
TriggerMin=0
TriggerMax=255
Rumble=1000
L_Linearity=300
L_Deadzone=0
L_AntiDeadzone=40
R_Linearity=300
R_Deadzone=0
R_AntiDeadzone=40
Remap=00 01 02 03 04 05 06 07 08 09 10 11 12 13 14 15 16 17 18 19 20 21 22 23"

**Comment by SnowGabe** [comment]
I just noticed that I was using "controller 0", "port=0".

**Comment by KrossX** [comment]
That's fine, it's the default index for it. By default, controller# should match with port#

You can test if you put the dll in the proper place by deleting the INI file, as a new file should be created in place when you run the game. The dll should be in the same location as the main game executable.

**Comment by SnowGabe** [comment]
The files are in the same place as the game executable.

**Comment by KrossX** [comment]
Hmm... are you using the 32bit or 64bit version of the dll? I think it's the 32bit version for that game.

**Comment by SnowGabe** [comment]
Sorry for the late reply.
I got the game working with the 32-bit version. I don't notice any deadzone (R_AntiDeadzone=504; L_AntiDeadzone=504) .

Thank you for this tool!
