### ISSUE TITLE
Controller isnt working in most games any more

### ISSUE THREAD

**Issue by FGay** [KrossX/Durazno#40]
I tried to reconfigure the sensitivity of the sticks on my Xbox One controller and i was very impressed by the simple design of your software and that it is free.
I tried it first on GTA V but it didn't seem to do anything and after a while i tried to replace the durazno dll files with my xinput files in System32 and sysWOW64 but this didnt work out so i already replaced them with the original dll files because i made a backup of these.
the next day when i tried to play GTA or Arma my controller didn't work properly. 
No matter how softly i moved the sticks at some point it was activating completely (for example i move the stick a tiny bit to the right and it is like i'm holding down the D key. some games are not affected (rocket league, watch dogs, rainbow six siege for example). I had the same problem with the game Argo (which is built on arma) but i was able to repair it by putting your dll files into the game directory but sadly that does not work for arma 3 and gta v. 
I looked at Arma 3 and it just loaded Xinput dll files from system32 which are the original files. I have no idea what i have done so horribly wrong but i hope you can help me.

**Comment by KrossX** [comment]
Durazno is a wrapper and it operates between the game and the real dlls. That works by exploting how Windows looks for dll files, placing Durazno besides the game main executable makes the game (hopefully) load Durazno which itself loads the real dlls.

Assuming the system files are untouched, just remove the xinput dll files from the game's directory and that shoule make things go back to normal.

As for using Durazno, you must match bits and version used. If GTA V is a 64bit game, it requires the 64bit Durazno dll.

**Comment by FGay** [comment]
i tried putting the durazno files into my GTA V folder and then looked at what dll files GTA was loading and it loaded the Durazno files but it also loaded the system 32 files afterwards so i guess the durazno files were overwritten by them. i still have the same problem i also tried removing all Durazno files but it didnt help. Some games dont even allow to load custom dll files for cheat protection even if they are in located in system 32 (arma 3 is one of them).
i am guessing that either durazno or i myself messed up something that is located between the raw input of controller data and xinput processing. i remember that i also installed reWASD but i think my controller still worked after the deinstallation of reWASD.

**Comment by KrossX** [comment]
The system32 would be loaded always, Durazno loads them as they're necessary. Durazno is a wrapper, not a replacement. If the game itself loads the system files after detecting Durazno, that's it. Durazno won't work in that case as it does not use hooks.

Removing the xinput dll files from the game directory should restore normal functionality. Otherwise, you might have messed up with system files. To correct system files, run sfc /scannow from an admin command prompt and/or try reinstalling latest DirectX as it includes some system xinput files.

**Comment by FGay** [comment]
ok, solved it.
Turns out it was jsut steam and not durazno.
steam told any steam game that i have a steam controller and it tried to map it to xbox 360 controller but it didnt work because i dont have a steam controller.

**Comment by KrossX** [comment]
Damn, that's just mean. At least you solved it.
