### ISSUE TITLE
Game ignores Durazno files

### ISSUE THREAD

**Issue by Teppopups** [KrossX/Durazno#43]
Hi,

Xbox 360 Controller here.

Sniper Elite 4 game just ignores Durazno files. Configured as described in (very brief) manual, put .ini and all the .dll's near .exe. The game has two .exe files: dx12 and dx11 version, tried both, first one requires xinput1_4.dll, second one - xinput9_1_0.dll (according to dependency walker). No beep sound, no log file, no mappings, nothing. Seems the .exe is 64 bit, but also tried x86 files - no result. Even reinstalled the Visual C++ Redistributable for Visual Studio 2015 to slightly earlier rbuild (v14.0.23026) - nothing.

Other utilities like x360ce and XInput Plus work fine. But I can't use them because of their limitations: x360ce does not allow using both triggers simultaneously, wich I need; XInput Plus does not have anti-deadzone feature, which I actually need very much!

Please Help!

**Comment by ikoimecs** [comment]
Wow!!!

Finally, managed to get it working! The game has multiple .exe files in different folders:
1) stp-se4dx12.exe (and *11.exe) in game root folder ../ which be used to start the game (no xinput*.dll dependencies);
2) SniperElite4.exe which I start from desktop shortcut, in ../Launcher folder (no xinput*.dll dependencies);
3) SniperElite4_DX12.exe (and *11.exe) int ../bin folder (which do have xinput*.dll dependency) I cannot start the game from them.

I put the .ini and .dll's in all three folders and it works!

**Comment by KrossX** [comment]
Excellent! I was looking to see if I could test the game but I don't even have the hdd space.
