### ISSUE TITLE
Trigger settings error with GUI

### ISSUE THREAD

**Issue by Dyrewulfe** [KrossX/Durazno#49]
[Right here](https://github.com/KrossX/Durazno/blob/f7c18c2b31cb7bec0eb44f78a65307651a556106/DuraznoGUI/INIsettings.cs#L114)

Looks like it was a missed copy-pasta edit(been there done that). LTrigger gets assigned then overwritten by RTrigger, RTrigger gets defaulted.

**Comment by KrossX** [comment]
That's some evil bug indeed! Thanks for spotting it.

**Comment by Dyrewulfe** [comment]
You're welcome, happy to help. I figured it flew under the radar because triggers need manual edits anyways(I think? Didn't see a way to change them in the gui.)

**Comment by KrossX** [comment]
I probably tried to just leave the work there in case I wanted to modify the GUI at some point. But I haven't event installed that program in a long time, MS Blend I think it was.
