### ISSUE TITLE
"Durazno stopped working" with Dark Souls II Scholar of the First Sin on Win 8.1

### ISSUE THREAD

**Issue by Arcademic** [KrossX/Durazno#5]
Copied the 64bit files from Durazno v0.6-18 to my game folder, but when I want to start durazno.exe I get "Durazno XInput Wrapper GUI stopped working".

**Comment by KrossX** [comment]
Try using the GUI elsewhere then copy only the INI and DLL files. Do not copy the GUI.

**Comment by Arcademic** [comment]
Answered within 5 minutes and solved my problem, thank you very much!
