### ISSUE TITLE
Does not increase right stick deadzone in RL 

### ISSUE THREAD

**Issue by JohnSt99** [KrossX/Durazno#53]
XBOX One S controller

![image](https://user-images.githubusercontent.com/17860067/131369471-161758a9-6ffe-430c-8d16-cbe73cea68f4.png)

Goal: 0.11 deadzone on left stick and 0.18 or higher on right stick 

I am on Epic and have restarted the game after applying both 32 bit and 64 bit, as well as applied while the game was closed

**Comment by KrossX** [comment]
Wrong issue tracker I'm afraid. This appears to be a quite modified version of Durazno, check on the upper right as it seems to have a link for "Help and updates" which might be worth checking out.
