### ISSUE TITLE
Mouse sensitivity (acceleration, inertia)?

### ISSUE THREAD

**Issue by Hexaae** [KrossX/Durazno#57]
Wondering if Durazno could (feature request for next version?) alter mouse input too, to change **acceleration and inertia**...
There are some games (e.g. Arkanoid Eternal Battle) which are missing a decent mouse fine tuning, and was looking for some tools to change this per-game, like Durazno does for controllers.

**Comment by KrossX** [comment]
Durazno it's only a XInput wrapper, there's no mouse data to alter. 

There are many ways to get mouse data, for DirectInput this projects might help: [dinputto8](https://github.com/elishacloud/dinputto8), [dxwrapper](https://github.com/elishacloud/dxwrapper), [dinput8wrapper](https://github.com/geeky/dinput8wrapper). Or for something driver based, you might wanna check this projects: [InterAccel](https://github.com/KovaaK/InterAccel), [rawaccel](https://github.com/a1xd/rawaccel)
