### ISSUE TITLE
Deadzone not integrating

### ISSUE THREAD

**Issue by juhy89** [KrossX/Durazno#7]
Hello. My right anolog stick is so messed up that i have to crank the deadzone all the way up to get a response in the test, but when i load up a game it doesn't change a thing. No matter the game, the changes i make to my controller's deadzone doesn't affect ingame experiences at all.

**Comment by juhy89** [comment]
And neither the 32 or the 64 bit versions work.

**Comment by KrossX** [comment]
What game is it, and how's your procedure to use it with the game?

**Comment by juhy89** [comment]
Any game at all. After i found out that i had a stick ghosting problem i used your software to increase my deadzone on the right stick. then i booted up the game, and no difference. On the test screen in Durazno it works fine, the top shows my normal ghosting and the bottom shows the fixed stick output with the deadzone increase. But as soon as I try to use it in a game the changes I made in Durazno aren't detected and I get my normal ghosting problem.

**Comment by KrossX** [comment]
You need to copy the ini and dll file into the game directory for it to work. The game must be using the XInput API, and might require the dll to be renamed depending on which API version the game uses.

**Comment by juhy89** [comment]
How do I tell what api it uses? and what would i have to rename it to?

**Comment by juhy89** [comment]
well i figured out my last question, and it didnt work. i tried TERA, which uses that API. after I replaced it, it still doesnt work.

**Comment by KrossX** [comment]
For TERA, it seems the file should go under TERA/Client/Binaries with the default name. Just copying the dll and the ini file you created with your settings should've been enough.

You could try deleting the ini file, run TERA normally and then check the Binaries directory to see if a new settings file was created. Otherwise, the durazno dll didn't initialize.

**Comment by juhy89** [comment]
It still does not work. Nothing works. Your software just doesn't work for me no matter what I do it seems.

**Comment by KrossX** [comment]
So it seems. You should give XInput Plus a try then.

http://pcgamingwiki.com/wiki/Glossary:Controller#XInput_Plus
